Reference: https://stackoverflow.com/questions/49433936/how-to-initialize-weights-in-pytorch

In [ ]:
import torch
import torch.nn as nn 

In [ ]:
input = torch.ones((4,4))
print(input)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
d = nn.Linear(4,4,bias=False)

In [ ]:
d

Linear(in_features=4, out_features=4, bias=False)

In [ ]:
d.weight.data=torch.full((4,4),0.0)
print(d.weight.data)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:
d(input)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], grad_fn=<MmBackward>)

Answer: If we are initializing weights by 0.0, then the output matrix will also have zero

1.   H=X*W1
2.   O=H*W2

